import type {TransactionType} from '@/types';

export const transactions: TransactionType[] = [
  {
    id: 1,
    date: 'Today',
    name: 'Adalyn Roth',
    category: 'Money transfer',
    amount: 140.0,
    icon: '/icons/09.png',
    direction: 'out',
  },
  {
    id: 2,
    date: 'Today',
    name: 'Amazon',
    category: 'Online payments',
    amount: 239.57,
    icon: '/icons/02.png',
    direction: 'out',
  },

  {
    id: 3,
    date: 'Sep 10, 2022',
    name: 'Paypal',
    category: 'Deposits',
    amount: 700.0,
    icon: '/icons/21.png',
    direction: 'in',
  },
  {
    id: 3,
    date: 'Sep 10, 2022',
    name: 'ATM',
    category: 'Cash withdrawal',
    amount: 1200.0,
    icon: '/icons/24.png',
    direction: 'out',
  },
  {
    id: 4,
    date: 'Sep 10, 2022',
    name: 'eBay',
    category: 'Online payments',
    amount: 287.84,
    icon: '/icons/25.png',
    direction: 'out',
  },
  {
    id: 5,
    date: 'Sep 5, 2022',
    name: '+17869871235',
    category: 'Mobile payment',
    amount: 10.0,
    icon: '/icons/10.png',
    direction: 'out',
  },
  {
    id: 6,
    date: 'Sep 5, 2022',
    name: 'Maribel Farrell',
    category: 'Money transfer',
    amount: 568.0,
    icon: '/icons/09.png',
    direction: 'in',
  },
  {
    id: 7,
    date: 'Sep 5, 2022',
    name: 'Electricity',
    category: 'Utility bills',
    amount: 198.27,
    icon: '/icons/12.png',
    direction: 'out',
  },
];
